import { useEffect, useState } from "react";

function ApiAutod() {
  const [autod, setAutod] = useState([]);
     // uef
     useEffect(() => {
         fetch("https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/all-vehicles-model/records?limit=100")
         .then(res => res.json())
         .then(json => setAutod(json.results))
     }, []);
   return (
     <div>
          <table>
          <thead>
            <tr>
              <th>Make</th>
              <th>Model</th>
              <th>Barrels08</th>
              <th>Barrelsa08</th>
              <th>Charge120</th>
              <th>Charge240</th>
              <th>City08</th>
              <th>City08u</th>
              <th>Citya08</th>
              <th>Citya08u</th>
              <th>Citycd</th>
              <th>Citye</th>
              <th>Cityuf</th>
              <th>Co2</th>
              <th>Co2a</th>
              <th>Co2tailpipeagpm</th>
              <th>Co2tailpipegpm</th>
              <th>Comb08</th>
              <th>Comb08u</th>
              <th>Comba08</th>
              <th>Comba08u</th>
              <th>Combe</th>
              <th>Combinedcd</th>
              <th>Combineduf</th>
              <th>Cylinders</th>
              <th>Displ</th>
              <th>Drive</th>
              <th>Engid</th>
              <th>Eng_dscr</th>
              <th>Fescore</th>
              <th>Fuelcost08</th>
              <th>Fuelcosta08</th>
              <th>Fueltype</th>
              <th>Fueltype1</th>
              <th>Ghgscore</th>
              <th>Ghgscorea</th>
              <th>Highway08</th>
              <th>Highway08u</th>
              <th>Highwaya08</th>
              <th>Highwaya08u</th>
              <th>Highwaycd</th>
              <th>Highwaye</th>
              <th>Highwayuf</th>
              <th>Hlv</th>
              <th>Hpv</th>
              <th>Id</th>
              <th>Lv2</th>
              <th>Lv4</th>
              <th>Mpgdata</th>
              <th>Phevblended</th>
              <th>Pv2</th>
              <th>Pv4</th>
              <th>Range</th>
              <th>Rangecity</th>
              <th>Rangecitya</th>
              <th>Rangehwy</th>
              <th>Rangehwya</th>
              <th>Trany</th>
              <th>Ucity</th>
              <th>Ucitya</th>
              <th>Uhighway</th>
              <th>Uhighwaya</th>
              <th>Vclass</th>
              <th>Year</th>
              <th>Yousavespend</th>
              <th>Guzzler</th>
              <th>Trans_dscr</th>
              <th>Tcharger</th>
              <th>Scharger</th>
              <th>Atvtype</th>
              <th>Fueltype2</th>
              <th>Rangea</th>
              <th>Evmotor</th>
              <th>Mfrcode</th>
              <th>C240dscr</th>
              <th>Charge240b</th>
              <th>C240bdscr</th>
              <th>Createdon</th>
              <th>Modifiedon</th>
              <th>Startstop</th>
              <th>Phevcity</th>
              <th>Phevhwy</th>
              <th>Phevcomb</th>
              <th>Basemodel</th>
            </tr>
          </thead>
          <tbody>
              {autod.map(auto =>
              <tr key={auto.id}>
              <td>{auto.make}</td>
              <td>{auto.model}</td>
              <td>{auto.barrels08}</td>
              <td>{auto.barrelsa08}</td>
              <td>{auto.charge120}</td>
              <td>{auto.charge240}</td>
              <td>{auto.city08}</td>
              <td>{auto.city08u}</td>
              <td>{auto.citya08}</td>
              <td>{auto.citya08u}</td>
              <td>{auto.citycd}</td>
              <td>{auto.citye}</td>
              <td>{auto.cityuf}</td>
              <td>{auto.co2}</td>
              <td>{auto.co2a}</td>
              <td>{auto.co2tailpipeagpm}</td>
              <td>{auto.co2tailpipegpm}</td>
              <td>{auto.comb08}</td>
              <td>{auto.comb08u}</td>
              <td>{auto.comba08}</td>
              <td>{auto.comba08u}</td>
              <td>{auto.combe}</td>
              <td>{auto.combinedcd}</td>
              <td>{auto.combineduf}</td>
              <td>{auto.cylinders}</td>
              <td>{auto.displ}</td>
              <td>{auto.drive}</td>
              <td>{auto.engid}</td>
              <td>{auto.eng_dscr}</td>
              <td>{auto.fescore}</td>
              <td>{auto.fuelcost08}</td>
              <td>{auto.fuelcosta08}</td>
              <td>{auto.fueltype}</td>
              <td>{auto.fueltype1}</td>
              <td>{auto.ghgscore}</td>
              <td>{auto.ghgscorea}</td>
              <td>{auto.highway08}</td>
              <td>{auto.highway08u}</td>
              <td>{auto.highwaya08}</td>
              <td>{auto.highwaya08u}</td>
              <td>{auto.highwaycd}</td>
              <td>{auto.highwaye}</td>
              <td>{auto.highwayuf}</td>
              <td>{auto.hlv}</td>
              <td>{auto.hpv}</td>
              <td>{auto.id}</td>
              <td>{auto.lv2}</td>
              <td>{auto.lv4}</td>
              <td>{auto.mpgdata}</td>
              <td>{auto.phevblended}</td>
              <td>{auto.pv2}</td>
              <td>{auto.pv4}</td>
              <td>{auto.range}</td>
              <td>{auto.rangecity}</td>
              <td>{auto.rangecitya}</td>
              <td>{auto.rangehwy}</td>
              <td>{auto.rangehwya}</td>
              <td>{auto.trany}</td>
              <td>{auto.ucity}</td>
              <td>{auto.ucitya}</td>
              <td>{auto.uhighway}</td>
              <td>{auto.uhighwaya}</td>
              <td>{auto.vclass}</td>
              <td>{auto.year}</td>
              <td>{auto.yousavespend}</td>
              <td>{auto.guzzler}</td>
              <td>{auto.trans_dscr}</td>
              <td>{auto.tcharger}</td>
              <td>{auto.scharger}</td>
              <td>{auto.atvtype}</td>
              <td>{auto.fueltype2}</td>
              <td>{auto.rangea}</td>
              <td>{auto.evmotor}</td>
              <td>{auto.mfrcode}</td>
              <td>{auto.c240dscr}</td>
              <td>{auto.charge240b}</td>
              <td>{auto.c240bdscr}</td>
              <td>{auto.createdon}</td>
              <td>{auto.modifiedon}</td>
              <td>{auto.startstop}</td>
              <td>{auto.phevcity}</td>
              <td>{auto.phevhwy}</td>
              <td>{auto.phevcomb}</td>
              <td>{auto.basemodel}</td>
            </tr>)}
          </tbody>
        </table>
     </div>
   )
}

export default ApiAutod